### ISSUE TITLE
Use celery 4 instread of celery 3 and dj-celery

### ISSUE THREAD

**Issue by awemulya** [TeamNobi/Nobi#10]
For better monitoring like flowers and celery 4 methods.

**Comment by awemulya** [comment]
https://github.com/kobotoolbox/kobocat/commits/master finally they have updated celery. Lets check this on our server @raeesaroj

**Comment by raeesaroj** [comment]
@awemulya  that's great.

**Comment by jd-alexander** [comment]
nice!
