### ISSUE TITLE
Project creation error if log out of one account into another

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#13]
It seems if you log out of one account and then log into another there are errors. When I open an incognito window and log in I am able to create a project but if it's in the same window then it doesn't work.
This is printed in the console 

> Failed to load resource: the server responded with a status of 403 ()

 I see this error. 
<img width="522" alt="screen shot 2019-02-23 at 9 17 55 pm" src="https://user-images.githubusercontent.com/1509205/53294248-05f21100-37b1-11e9-872a-19907fb25534.png">

**Comment by awemulya** [comment]
@SanipRijal Please reproduce this, Check this issue exists in kobotoolbox or did we miss anything on server config.

**Comment by jd-alexander** [comment]
Yes, this error seems to cause the most problems.

**Comment by awemulya** [comment]
This issue exists in main kobotoolbox code. Need to open issue there.

**Comment by jd-alexander** [comment]
Okay but they take so long to fix

**Comment by awemulya** [comment]
@jd-alexander We will present you the details of this bug.
currently logout of systems, clear cache to use multi accounts.

**Comment by jd-alexander** [comment]
Okay thank you
