### ISSUE TITLE
Error when I try to load a report in Nobi Forms 

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#18]
I get this error when I try to load a report 
`error: ServerSelectionTimeoutError at /reports/aSipKeN4tKuUU56sdzjHim/ mongo:27017: [Errno -3] Temporary failure in name resolution Request Method: GET Request URL: https://forms.nobiforms.com/reports/aSipKeN4tKuUU56sdzjHim/?names= Django Version: 1.8.19 Python Executable: /usr/bin/uwsgi-core Python Version: 2.7.15 Python Path: ['.', '', '/home/joel/.virtualenvs/nobi-forms/lib/python2.7', '/home/joel/.virtualenvs/nobi-forms/lib/python2.7/plat-x86_64-linux-gnu', '/home/joel/.virtualenvs/nobi-forms/lib/python2.7/lib-tk', '/home/joel/.virtualenvs/nobi-forms/lib/python2.7/lib-old', '/home/joel/.virtualenvs/nobi-forms/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/joel/.virtualenvs/nobi-forms/local/lib/python2.7/site-packages', '/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages', '/home/joel/.virtualenvs/nobi-forms/src/django-digest', '/home/joel/.virtualenvs/nobi-forms/src/formpack/src', '/srv/nobi/Nobi-forms'] Server time: Mon, 25 Feb 2019 06:54:51 +0000 Installed Applications: ('django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'reversion', 'debug_toolbar', 'mptt', 'haystack', 'private_storage', 'kobo.apps.KpiConfig', 'hub', 'loginas', 'webpack_loader', 'registration', 'django.contrib.admin', 'django_extensions', 'taggit', 'rest_framework', 'rest_framework.authtoken', 'oauth2_provider', 'markitup', 'django_digest', 'kobo.apps.superuser_stats', 'kobo.apps.service_health', 'constance', 'constance.backends.database', 'kobo.apps.hook', 'django_celery_beat') Installed Middleware: (u'debug_toolbar.middleware.DebugToolbarMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'hub.middleware.OtherFormBuilderRedirectMiddleware') Traceback: File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response 132. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view 58. return view_func(*args, **kwargs) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/rest_framework/viewsets.py" in view 90. return self.dispatch(request, *args, **kwargs) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/rest_framework/views.py" in dispatch 489. response = self.handle_exception(exc) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/rest_framework/views.py" in handle_exception 449. self.raise_uncaught_exception(exc) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/rest_framework/views.py" in dispatch 486. response = handler(request, *args, **kwargs) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/rest_framework/mixins.py" in retrieve 58. return Response(serializer.data) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/rest_framework/serializers.py" in data 263. self._data = self.to_representation(self.instance) File "./kobo/apps/reports/serializers.py" in to_representation 27. _list = report_data.data_by_identifiers(obj, vnames, split_by=split_by) File "./kobo/apps/reports/report_data.py" in data_by_identifiers 178. split_by=split_by) File "/home/joel/.virtualenvs/nobi-forms/src/formpack/src/formpack/reporting/autoreport.py" in get_stats 219. return self._calculate_stats(submissions, fields, self.versions, lang) File "/home/joel/.virtualenvs/nobi-forms/src/formpack/src/formpack/reporting/autoreport.py" in _calculate_stats 58. for entry in submissions: File "./kobo/apps/reports/report_data.py" in <genexpr> 108. _infer_version_id(submission) for submission in submission_stream File "./kpi/deployment_backends/kobocat_backend.py" in <genexpr> 548. MongoDecodingHelper.to_readable_dict(instance) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/pymongo/cursor.py" in next 1189. if len(self.__data) or self._refresh(): File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/pymongo/cursor.py" in _refresh 1087. self.__session = self.__collection.database.client._ensure_session() File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/pymongo/mongo_client.py" in _ensure_session 1563. return self.__start_session(True, causal_consistency=False) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/pymongo/mongo_client.py" in __start_session 1516. server_session = self._get_server_session() File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/pymongo/mongo_client.py" in _get_server_session 1549. return self._topology.get_server_session() File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/pymongo/topology.py" in get_server_session 427. None) File "/home/joel/.virtualenvs/nobi-forms/lib/python2.7/site-packages/pymongo/topology.py" in _select_servers_loop 199. self._error_message(selector)) Exception Type: ServerSelectionTimeoutError at /reports/aSipKeN4tKuUU56sdzjHim/ Exception Value: mongo:27017: [Errno -3] Temporary failure in name resolution Request information: GET: names = u'' POST: No POST data FILES: No FILES data COOKIES: csrftoken = 'q22CuneTkcGj1pDtjuQDjVaHYtVCZ8qv' nobi_cookie = '.eJxVzEEOwiAQheG7zNoQSmFaXLr3DISZIaVqICntynh3bdKFXb__e28IcVtz2FpaQo4twxV6EhSnWXv0vbAmLzSYwVo0yXYYO8c8GjfC5R9T5Gcq8vPyiGWqimtZl5nUnqhjbepeJb1uR3s6mHeL8PkCzDMw5A:1gy9Xt:20qfY4J48bmgWmJ_p-qWG-g5CSE' META: wsgi.multiprocess = True HTTP_REFERER = 'https://forms.nobiforms.com/' SCRIPT_NAME = u'' REQUEST_METHOD = 'GET' PATH_INFO = u'/reports/aSipKeN4tKuUU56sdzjHim/' SERVER_PROTOCOL = 'HTTP/2.0' QUERY_STRING = 'names=' CONTENT_LENGTH = '' HTTP_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36' HTTP_COOKIE = 'csrftoken=q22CuneTkcGj1pDtjuQDjVaHYtVCZ8qv; nobi_cookie=".eJxVzEEOwiAQheG7zNoQSmFaXLr3DISZIaVqICntynh3bdKFXb__e28IcVtz2FpaQo4twxV6EhSnWXv0vbAmLzSYwVo0yXYYO8c8GjfC5R9T5Gcq8vPyiGWqimtZl5nUnqhjbepeJb1uR3s6mHeL8PkCzDMw5A:1gy9Xt:20qfY4J48bmgWmJ_p-qWG-g5CSE"' SERVER_NAME = 'forms.nobiforms.com' REMOTE_ADDR = '104.244.229.57' wsgi.url_scheme = 'https' SERVER_PORT = '443' uwsgi.node = 'docker-s-3vcpu-1gb-fra1-01' DOCUMENT_ROOT = '/srv/nobi/Nobi-forms' HTTP_X_REQUESTED_WITH = 'XMLHttpRequest' wsgi.input = <uwsgi._Input object at 0x7f6236b6c408> HTTP_HOST = 'forms.nobiforms.com' HTTPS = 'on' wsgi.multithread = False REQUEST_URI = '/reports/aSipKeN4tKuUU56sdzjHim/?names=' HTTP_ACCEPT = 'application/json, text/javascript, */*; q=0.01' wsgi.version = wsgi.run_once = False wsgi.errors = <open file 'wsgi_errors', mode 'w' at 0x7f623782a9c0> REMOTE_PORT = '32545' HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9' REQUEST_SCHEME = 'https' uwsgi.version = '2.0.15-debian' CONTENT_TYPE = '' wsgi.file_wrapper = '' CSRF_COOKIE = u'q22CuneTkcGj1pDtjuQDjVaHYtVCZ8qv' HTTP_ACCEPT_ENCODING = 'gzip, deflate, br' Settings: Using settings module kobo.settings MARKITUP_FILTER = CORS_URLS_REGEX = '^/assets/.*$' SECURE_BROWSER_XSS_FILTER = False HAYSTACK_SIGNAL_MODELS = USE_THOUSAND_SEPARATOR = False CSRF_COOKIE_SECURE = False LANGUAGE_CODE = 'en-us' ROOT_URLCONF = 'kobo.urls' MANAGERS = SKIP_HEAVY_MIGRATIONS = False BROKER_URL = 'redis://localhost:6379/0' BASE_DIR = '/srv/nobi/Nobi-forms' CELERY_TASK_SOFT_TIME_LIMIT = 1800 ACCOUNT_ACTIVATION_DAYS = 30 MAXIMUM_EXPORTS_PER_USER_PER_FORM = 10 SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer' STATIC_ROOT = '/srv/nobi/Nobi-forms/staticfiles' MONTH_DAY_FORMAT = 'F j' ALLOWED_HOSTS = ['*'] LANGUAGE_COOKIE_NAME = 'django_language' EMAIL_SUBJECT_PREFIX = '[Django] ' SERVER_EMAIL = 'hello@getnobi.com' SECURE_HSTS_SECONDS = 0 STATICFILES_FINDERS = SESSION_CACHE_ALIAS = 'default' SESSION_COOKIE_DOMAIN = '.nobiforms.com' SESSION_COOKIE_NAME = 'nobi_cookie' CSRF_COOKIE_NAME = 'csrftoken' CELERY_BROKER_URL = 'redis://localhost:6379/0' TIME_INPUT_FORMATS = SECURE_REDIRECT_EXEMPT = [] DATABASES = {'default': {'ENGINE': 'django.contrib.gis.db.backends.postgis', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'nobi_db', 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'UTC', 'PORT': '', 'HOST': 'localhost', 'USER': 'nobi_user', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {}}} EMAIL_SSL_KEYFILE = u'********************' FILE_UPLOAD_DIRECTORY_PERMISSIONS = None FILE_UPLOAD_PERMISSIONS = None MONGO_DB = Database(MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=True, connect=False, j=True), u'formhub') FILE_UPLOAD_HANDLERS = DEFAULT_CONTENT_TYPE = 'text/html' CELERY_TASK_TIME_LIMIT = 2100 GIT_REV = {'short': '467d770b', 'tag': False, 'long': '467d770b7893b8cfc2b4b123a2668d1f0884d0cf', 'branch': 'master'} APPEND_SLASH = True FIRST_DAY_OF_WEEK = 0 DATABASE_ROUTERS = [] DEFAULT_TABLESPACE = '' YEAR_MONTH_FORMAT = 'F Y' MONGO_DATABASE = {'HOST': 'mongo', 'PASSWORD': u'********************', 'NAME': 'formhub', 'USER': '', 'PORT': 27017} CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}} SESSION_COOKIE_PATH = '/' DEFAULT_DEPLOYMENT_BACKEND = 'kobocat' SECURE_CONTENT_TYPE_NOSNIFF = False MIDDLEWARE_CLASSES = USE_I18N = True THOUSAND_SEPARATOR = ',' SECRET_KEY = u'********************' REST_FRAMEWORK = {'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication', 'rest_framework.authentication.BasicAuthentication', 'rest_framework.authentication.TokenAuthentication'], 'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer', 'kpi.renderers.XMLRenderer'], 'URL_FIELD_NAME': 'url', 'PAGE_SIZE': 100, 'DEFAULT_PAGINATION_CLASS': 'kpi.serializers.Paginated'} CELERY_WORKER_MAX_TASKS_PER_CHILD = 7 CORS_ORIGIN_WHITELIST = DEFAULT_INDEX_TABLESPACE = '' REGISTRATION_EMAIL_HTML = False LOGGING_CONFIG = 'logging.config.dictConfig' SIGNING_BACKEND = 'django.core.signing.TimestampSigner' TEMPLATE_LOADERS = WSGI_APPLICATION = 'kobo.wsgi.application' INTERCOM_APP_ID = None TEMPLATE_DEBUG = False X_FRAME_OPTIONS = 'SAMEORIGIN' CELERY_BEAT_SCHEDULE = {'send-hooks-failures-reports': {'task': 'kobo.apps.hook.tasks.failures_reports', 'schedule': <crontab: 0 0 * * * (m/h/d/dM/MY)>}} HAYSTACK_CONNECTIONS = {'default': {'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine', 'PATH': './kobo/whoosh_index'}} EMAIL_HOST_PASSWORD = u'********************' USE_X_FORWARDED_HOST = False EMAIL_TIMEOUT = None SECURE_SSL_HOST = None DEFAULT_CHARSET = 'utf-8' SESSION_COOKIE_SECURE = False MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage' CSRF_COOKIE_DOMAIN = None FILE_CHARSET = 'utf-8' DEBUG = True PRIVATE_STORAGE_ROOT = '/srv/nobi/Nobi-forms/media' MONGO_CONNECTION = MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=True, connect=False, j=True) LANGUAGE_COOKIE_DOMAIN = None DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage' INSTALLED_APPS = LANGUAGES_BIDI = USE_L10N = True ENKETO_SERVER = 'https://enketoexpress.forms.nobiforms.com/' STATICFILES_DIRS = PREPEND_WWW = False SECURE_PROXY_SSL_HEADER = None LANGUAGE_COOKIE_AGE = None SESSION_COOKIE_HTTPONLY = True DEBUG_PROPAGATE_EXCEPTIONS = False INTERNAL_IPS = MEDIA_URL = '/media/' EMAIL_FILE_PATH = '/srv/nobi/Nobi-forms/emails' GOOGLE_ANALYTICS_TOKEN = u'********************' LOGIN_URL = '/accounts/login/' SESSION_EXPIRE_AT_BROWSER_CLOSE = False TIME_FORMAT = 'P' AUTH_USER_MODEL = 'auth.User' DATE_INPUT_FORMATS = AUTHENTICATION_BACKENDS = FORCE_SCRIPT_NAME = None PASSWORD_RESET_TIMEOUT_DAYS = u'********************' SESSION_FILE_PATH = None CACHE_MIDDLEWARE_ALIAS = 'default' SESSION_SAVE_EVERY_REQUEST = False STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage' NUMBER_GROUPING = 0 SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies' CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure' CSRF_COOKIE_PATH = '/' LOGIN_REDIRECT_URL = '/' DECIMAL_SEPARATOR = '.' CACHE_MIDDLEWARE_KEY_PREFIX = u'********************' LOCALE_PATHS = '/srv/nobi/Nobi-forms/locale' KOBOCAT_INTERNAL_URL = 'https://api.forms.nobiforms.com' TEMPLATE_STRING_IF_INVALID = '' ENKETO_VERSION = 'express' RAVEN_JS_DSN = None LOGOUT_URL = '/accounts/logout/' EMAIL_USE_TLS = True FIXTURE_DIRS = EMAIL_HOST = 'smtp.gmail.com' DATE_FORMAT = 'N j, Y' WHOOSH_PATH = './kobo/whoosh_index' DKOBO_PREFIX = False CAN_LOGIN_AS = <function <lambda> at 0x7f6252e36758> MEDIA_ROOT = '/srv/nobi/Nobi-forms/media' LANGUAGE_COOKIE_PATH = '/' DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter' ADMINS = [('Amulya', 'awemulya@gmail.com'), ('saroj', 'raesaroj16@gmail.com'), ('sanip', 'saneprijal@gmail.com')] FORMAT_MODULE_PATH = None DEFAULT_FROM_EMAIL = 'hello@getnobi.com' SECURE_HSTS_INCLUDE_SUBDOMAINS = False CONSTANCE_CONFIG = {'SOURCE_CODE_URL': ('https://github.com/kobotoolbox/', 'URL of source code repository. When empty, a link will not be shown in the user interface'), 'TERMS_OF_SERVICE_URL': ('http://www.kobotoolbox.org/terms', 'URL for terms of service document'), 'SUPPORT_URL': ('http://help.kobotoolbox.org/', 'URL of user support portal. When empty, a link will not be shown in the user interface'), 'HOOK_MAX_RETRIES': (3, 'Number of times the system will retry to send data to remote server before giving up'), 'ALLOW_UNSECURED_HOOK_ENDPOINTS': (True, 'Allow the use of unsecured endpoints for hooks. (e.g http://hook.example.com)'), 'PRIVACY_POLICY_URL': ('http://www.kobotoolbox.org/privacy', 'URL for privacy policy'), 'REGISTRATION_OPEN': (True, 'Allow new users to register accounts for themselves'), 'SUPPORT_EMAIL': ('help@kobotoolbox.org', 'Email address for users to contact, e.g. when they encounter unhandled errors in the application')} ENKETO_INTERNAL_URL = 'https://enketo.org/' DATETIME_FORMAT = 'N j, Y, P' TEMPLATE_DIRS = KOBOCAT_URL = 'https://api.forms.nobiforms.com' SEND_ACTIVATION_EMAIL = True ENKETO_URL = 'https://enketoexpress.forms.nobiforms.com' CELERY_TIMEZONE = 'UTC' DISALLOWED_USER_AGENTS = ALLOWED_INCLUDE_ROOTS = ENKETO_PREVIEW_URI = 'preview' EXTRA_LANG_INFO = {u'ku': {u'code': u'ku', u'name': u'Kurdish', u'bidi': True, u'name_local': u'\u0643\u0648\u0631\u062f\u06cc'}} LOGGING = {'loggers': {'console_logger': {'handlers': ['console'], 'propagate': True, 'level': 'DEBUG'}, 'django.db.backends': {'level': 'ERROR', 'propagate': True, 'handlers': ['console']}}, 'version': 1, 'formatters': {'simple': {'format': '%(levelname)s %(message)s'}, 'verbose': {'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'}}, 'disable_existing_loggers': False, 'handlers': {'console': {'formatter': 'verbose', 'class': 'logging.StreamHandler', 'level': 'DEBUG'}}} SHORT_DATE_FORMAT = 'm/d/Y' TEMPLATES = [{'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'debug': True, 'context_processors': ['django.contrib.auth.context_processors.auth', 'django.template.context_processors.debug', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static', 'django.template.context_processors.tz', 'django.contrib.messages.context_processors.messages', 'kpi.context_processors.external_service_tokens', 'kpi.context_processors.email', 'kpi.context_processors.sitewide_messages', 'kpi.context_processors.config']}, 'BACKEND': 'django.template.backends.django.DjangoTemplates'}] EXPOSE_GIT_REV = False TEST_RUNNER = 'kobo.settings.DoNotUseRunner' IGNORABLE_404_URLS = SECURE_SSL_REDIRECT = False TIME_ZONE = 'UTC' REGISTRATION_AUTO_LOGIN = True FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' CSRF_COOKIE_HTTPONLY = False CELERYD_MAX_CONCURRENCY = 6 ENKETO_SURVEY_ENDPOINT = 'api/v2/survey/all' EMAIL_USE_SSL = False TEMPLATE_CONTEXT_PROCESSORS = CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend' KPI_PREFIX = False MIGRATION_MODULES = {} MONGO_CONNECTION_URL = 'mongodb://mongo:27017' SESSION_COOKIE_AGE = 1209600 SETTINGS_MODULE = 'kobo.settings' USE_ETAGS = False LANGUAGES = [('en', u'English')] HAYSTACK_SIGNAL_PROCESSOR = 'kpi.haystack_utils.SignalProcessor' FILE_UPLOAD_TEMP_DIR = None CSRF_COOKIE_AGE = 31449600 STATIC_URL = '/static/' WEBPACK_LOADER = {'DEFAULT': {'BUNDLE_DIR_NAME': 'jsapp/compiled/', 'POLL_INTERVAL': 0.5, 'TIMEOUT': 5}} EMAIL_PORT = 587 PRIVATE_STORAGE_AUTH_FUNCTION = 'kpi.utils.private_storage.superuser_or_username_matches_prefix' USE_TZ = True SHORT_DATETIME_FORMAT = 'm/d/Y P' TEST_NON_SERIALIZED_APPS = [] ENKETO_API_TOKEN = u'********************' PASSWORD_HASHERS = u'********************' ABSOLUTE_URL_OVERRIDES = {} SILENCED_SYSTEM_CHECKS = [] KOBOCAT_DEFAULT_PERMISSION_CONTENT_TYPES = [('main', 'userprofile'), ('logger', 'xform'), ('api', 'project'), ('api', 'team'), ('api', 'organizationprofile'), ('logger', 'note')] UPCOMING_DOWNTIME = False CACHE_MIDDLEWARE_SECONDS = 600 EMAIL_SSL_CERTFILE = None ALLOWED_ANONYMOUS_PERMISSIONS = ANONYMOUS_USER_ID = -1 DATETIME_INPUT_FORMATS = KOBO_SURVEY_PREVIEW_EXPIRATION = 24 EMAIL_HOST_USER = 'hello@getnobi.com' You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.`

**Comment by awemulya** [comment]
Fixed, Missing mongo settings for report.
