### ISSUE TITLE
Open not working for forms.

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#20]
When I try to click on open to open enketo instance for data viewing and collection nothing works.

<img width="1161" alt="screen shot 2019-02-25 at 7 56 12 pm" src="https://user-images.githubusercontent.com/1509205/53379491-bdb12b00-3937-11e9-9319-8c0be3f3dcbc.png">

**Comment by awemulya** [comment]
![screenshot from 2019-03-01 09-39-54](https://user-images.githubusercontent.com/5351212/53615479-28978600-3c06-11e9-9779-997fa0a759c8.png)

Fixed enketo authentication changed in latest kpi,

**Comment by jd-alexander** [comment]
Thanks good sir
