### ISSUE TITLE
Change Android Application - KoboCollect to Nobi Forms

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#21]
Change KoboCollect to Nobi Forms for both links and change the link to `https://nobiforms.com/app/`

<img width="1082" alt="screen shot 2019-02-25 at 8 15 06 pm" src="https://user-images.githubusercontent.com/1509205/53380097-29949300-393a-11e9-82b2-f61437791228.png">

**Comment by awemulya** [comment]
where do you get this page from??

**Comment by jd-alexander** [comment]
I got it from under FORM
<img width="1430" alt="screen shot 2019-02-25 at 8 21 06 pm" src="https://user-images.githubusercontent.com/1509205/53380311-f272b180-393a-11e9-8b82-f70582dd317f.png">

**Comment by awemulya** [comment]
Oh we missed that.
Can we get link of android app.

**Comment by jd-alexander** [comment]
I am still putting it on the store so just put it to[https://nobiforms.com/app/]( https://nobiforms.com/app/ )and I will redirect it to the right place later.
