### ISSUE TITLE
Can these links be removed from form builder

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#22]
Can these be removed from form builder

<img width="539" alt="screen shot 2019-02-27 at 9 56 41 am" src="https://user-images.githubusercontent.com/1509205/53531558-73f44c00-3ac1-11e9-888f-4bcc71fdf168.png">
<img width="438" alt="screen shot 2019-02-27 at 9 56 48 am" src="https://user-images.githubusercontent.com/1509205/53531559-73f44c00-3ac1-11e9-8d75-7b9174d28434.png">

**Comment by awemulya** [comment]
We can remove kobotool box image. But Wont change Enketo .

**Comment by jd-alexander** [comment]
Okay yes just read that enketo  has to stay
