### ISSUE TITLE
When I change validation status this error occurs.

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#23]
Does this functionality actually work?
<img width="689" alt="screen shot 2019-02-27 at 9 58 45 am" src="https://user-images.githubusercontent.com/1509205/53531601-92f2de00-3ac1-11e9-8c41-b2b240956f72.png">

**Comment by awemulya** [comment]
Please regenate this issue in kobotoolbox server.

**Comment by jd-alexander** [comment]
Okay will do

**Comment by awemulya** [comment]
They will be happy. You found two bugs on kobotoolbox (kpi) which is active.
