### ISSUE TITLE
Pull latest bug fixes and enhancements from kobo.

### ISSUE THREAD

**Issue by awemulya** [TeamNobi/Nobi#24]
Lets update the latest code from kobo.
new celery 4 in kpi and kobocat.
@raeesaroj or we just wait kpi to fix form builder issues.

**Comment by jd-alexander** [comment]
Will we be updating to the latest?

**Comment by awemulya** [comment]
We have updated to latest stable release.

**Comment by jd-alexander** [comment]
awesome thank you
