### ISSUE TITLE
Login background screen changes

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#6]
I want to change the login background image to this file. 

![signup_photo](https://user-images.githubusercontent.com/1509205/52966364-151e2c80-3375-11e9-850e-7ecb42813db8.png)

**Comment by awemulya** [comment]
Thats great !! Is this Image free to use.

**Comment by jd-alexander** [comment]
Yes, I got it from [Envato Elements](https://elements.envato.com/) so I have licensing.

**Comment by jd-alexander** [comment]
This is a much more compressed version of the image.

![background 1](https://user-images.githubusercontent.com/1509205/53021833-10668080-3428-11e9-8168-c5a5bfaea050.png)
