### ISSUE TITLE
HTTPS not working across the site

### ISSUE THREAD

**Issue by jd-alexander** [TeamNobi/Nobi#9]
Hey @raeesaroj for some reason I am not seeing HTTPS/SSL on the different domains. I thought it was something on my computer but it seems it's on any device. could you check it for me. Let me know if you need any help. In the doc I sent to you
<img width="611" alt="screen shot 2019-02-20 at 9 33 10 am" src="https://user-images.githubusercontent.com/1509205/53102538-e2ea0780-34f9-11e9-8394-f6fc730d2b6c.png">
 I have some instructions on how to generate the certificates so let me know if that will work or if I need to access my DNS provider to make changes. thanks.

**Comment by raeesaroj** [comment]
@jd-alexander I will check that.

**Comment by raeesaroj** [comment]
@jd-alexander could you please check once and verify it?

**Comment by jd-alexander** [comment]
@raeesaroj nice. It works now. thank you.

**Comment by jd-alexander** [comment]
@raeesaroj question would it be hard for the kpi to be called "app.nobiforms.com" I think seeing "forms.nobiforms.com" is a bit repetitive. Just wondering if that's alot of work or if it's simple maintenance change. Let me know. If it will cause issues then it can remain.
